### ISSUE TITLE
Caused by: java.lang.ClassNotFoundException: org.springframework.boot.context.embedded.FilterRegistrationBean

### ISSUE THREAD

**Issue by dariosaltarelli** [auth0/auth0-spring-security-api#11]
Class not found exception when using spring-boot-starter-parent version  2.0.0.BUILD-SNAPSHOT.
The class has been deprecated in 1.4.1.RELEASE and it has been removed in 2.0.0.BUILD-SNAPSHOT.

**Comment by dariosaltarelli** [comment]
I cannot push upstream branches with applied fixed. But it works by:

1) fixing the pom:
```
<!-- upgrade spring-boot-version -->
<spring-boot.version>1.4.1.RELEASE</spring-boot.version>
....
<!--Add dependency to commons codec -->
<dependency>
	<groupId>commons-codec</groupId>
	<artifactId>commons-codec</artifactId>
	<version>1.10</version>
</dependency>
```


2) Replace **org.springframework.boot.context.embedded.FilterRegistration** with **org.springframework.boot.web.servlet.FilterRegistrationBean.**

**Comment by adrogon** [comment]
Hello @dariosaltarelli,
#12 should answer to your issue. Please notice commons-codec is shipped in java-jwt.

**Comment by dariosaltarelli** [comment]
Hi @adrogon, 
It does indeed. For commons-codec somehow it was not picking it up via transitive dependencies so Base64 could not be resolved. Maybe a local issue to my system.

Thanks for the quick feedaback.

**Comment by lborgav** [comment]
@dariosaltarelli I cannot understood "2) Replace org.springframework.boot.context.embedded.FilterRegistration with org.springframework.boot.web.servlet.FilterRegistrationBean."

**Comment by revof11** [comment]
I had a similar issue.  My problem was the Spring Boot and Spring Cloud versions.  I put it here since this comes up as the first search result for "_Caused by: java.lang.ClassNotFoundException: org.springframework.boot.context.embedded.FilterRegistrationBean_"

| Import Dependency | Bad Version | Good Version |
| ------- | ------ | ------ |
| spring-boot-dependencies | 1.5.0-RELEASE | 1.5.2-RELEASE |
| spring-cloud-dependencies | Camden.SR3 | Camden.SR6 |

The key for me was really the upgrade to Camden.SR6.

**Comment by jonashackt** [comment]
Many thanks to @revof11 !! Saved me a lot of debugging hours :)

**Comment by kentTanL** [comment]
@dariosaltarelli How should I replace?
