### ISSUE TITLE
ROLES AuthorityStrategy in 1.0.x

### ISSUE THREAD

**Issue by adrogon** [auth0/auth0-spring-security-api#23]
In 0.3.x, the configuration property `auth0.authorityStrategy` could be set to `ROLES`, resulting in `authorities` being set based on the JWT `roles` claim.

In 1.0.0-rc.2, it looks like `AuthenticationJsonWebToken.getAuthorities()` only looks for the `scope` claim.

The following related questions:
- Are you going to allow `roles` as a configuration property again?
- Should we just extend `AuthenticationJsonWebToken` to look for `roles`, or is there a better way to achieve this?
- What is the proper way to use `scope`? We set `app_metadata` to `{"scope": "ROLE_ADMIN"}`, but that seems a little odd compared to the previous `{"roles": ["ROLE_ADMIN"]}`, especially in Angular when claiming the JWT with `params: { scope: 'openid scope' }`.

Thanks in advance.

**Comment by arcseldon** [comment]
@adrogon - Auth0 now (introduced midway through 2016 as an opt-in for Cloud Users) makes a clear distinction between a `Client` and a `Resource Server` - An API is by definition a Resource Server - and for that you now define `scopes` only - and these are applied to a JWT Access Token.  

With the "legacy" flows - it was acceptable to send a JWT ID Token to an API endpoint (this was standard practice as a flow before Resource Servers were introduced). For that reason, the pre-v1 API had to accommodate both types of requests - support to expect an ID Token with ROLES assigned, or GROUPS assigned, or a JWT Access Token (for RS support) with `scope` attributes assigned. Furthermore, because we were supporting both ID Tokens and Access Tokens,  it had to determine whether the Client Secret was Base64 encoded and so on too, or whether using RS256 (mostly used by Resource Server by default). Hence all the Strategies and extra Configuration plumbing. 

This API specifically targets correct usage of a Resource Server where the provided JWT Access Token shall contain `scope` attributes.  This relates to ongoing OIDC Conformance changes we are making - and makes a clear distinction between `authentication and OIDC` and `authorization and Oauth2`.  Please find information in our `docs` [here](https://auth0.com/docs/api-auth).  If you wish to get a sense of how you could have set up a Resource Server using the legacy API library (pre-v1) then please refer to this [sample](https://github.com/auth0-samples/auth0-spring-security-api-resource-server-sample).

**Comment by adrogon** [comment]
Hello @arcseldon,

Really appreciate the time you took on explaining. We are using the JWT for authentication purposes only, not authorization. We happened to use the previous ID Token's `roles` for convenience, but will move that to the API instead.

I'm not sure what `scope` should contain in the end, but we are not going to use it for holding roles or groups anyway.

If you have a couple of minutes to look at #24, that one might be more critical to us :) We have solutions, but your input is welcome.
Thank you again.

**Comment by arcseldon** [comment]
@adrogon - pleased it helped. FYI only - you can manipulate the access token scopes in similar way to how you could define a Rule previously for doing the same with id token etc.

```
function (user, context, callback) {
  // To Access Token
  context.accessToken['http://permissions'] = user.permissions;
  context.accessToken['http://groups'] = user.groups;
  context.accessToken['http://roles'] = user.roles;
  // To ID Token
  context.idToken['http://permissions'] = user.permissions;
  context.idToken['http://groups'] = user.groups;
  context.idToken['http://roles'] = user.roles;
  
  callback(null, user, context);
}
```

**Comment by KarmicJohn** [comment]
@arcseldon - Is it possible to then pull these namespaced permissions / groups / roles for authorization in our WebSecurityConfigurerAdapter?

It's not really clear how the switch to OIDC requiring namespaced claims via the Authorization Extension can then translate to authorization in Spring Security for securing endpoints in our API using the Groups / Roles / Permissions from the Authorization Extension...

Is this recommended? I'd prefer to use the Authorization Extension rather than the finer-grained API Scopes control, but after having typed that, I have now come across this [article](https://auth0.com/docs/architecture-scenarios/application/spa-api/part-2#configure-the-authorization-extension). Does that setup suggest using the Auth Extension along with the API, requires setting up all scopes the API will use, then create the same thing under Permissions, then the SPA will specify ALL possible Scopes when authenticating and the 2nd rule in that example will be responsible for parsing the Scopes on the auth_token down to only those that are valid for this actual user?

Switching over from custom auth to auth0 hasn't been quite the time-saving endeavor I had hoped to this point and really hoping there's a simple solution to somehow utilize these namespaced permissions/groups & roles on the Spring Boot API side, once authenticated in React via the Lock component. I have the login working with the namespaced custom claims in the token and can pass that on to Spring Boot API with .fullyAuthenticated() properly processing -- just need that next hurdle to consider these custom claims for authorizing requests and can't find examples for that particular need.

Hopefully that makes sense and any assistance is so very much appreciated.
