### ISSUE TITLE
no support for isEnabled(), isAccountNonLocked(), isAccountNonExpired()

### ISSUE THREAD

**Issue by jeacott1** [auth0/auth0-spring-security-api#27]
when using this provider, regardless that the user.isEnabled property is set = emailVerified,
 there is nothing to actually do any check of this and the following standard properties.

user.isAccountNonLocked()
user.isAccountNonExpired()

consider extending AbstractUserDetailsAuthenticationProvider where this logic is properly handled.

**Comment by hzalaz** [comment]
The library is meant to be used with access tokens obtain via OAuth exchange [in Auth0](https://auth0.com/docs/api-auth) so they are used to call an API where the token is the one who authorize the access. This allows the API to be separated from the Authorization Server (AS) and ideally if the user is either locked or disabled he should not be able to get a token from the AS. The expiration is handled for you by the jwt validation and it will reject any invalid token.

If you need more assistance please reach us via https://support.auth0.com

**Comment by jeacott1** [comment]
this doesnt make sense to me. are you saying that despite the jwt carrying this information already, the auth server should be called from the server on every request to check the nonlocked nonexpired status?

**Comment by hzalaz** [comment]
@jeacott1 this library is meant to be used by access tokens not id tokens. The id_token may hold that information (added via rules) but that token wont be used for the api call. 

If you check our https://auth0.com/docs/api-auth doc and the structure of the access_token, there is no such information by default since as I said before most of those validation should be done before issuing the token not when consuming the token. e.g. you can fail the Auth if the email is not verifier or issue an access token with less scopes until its verified.

In the case we wished to populate those methods, we need to specify a way to map the custom claim to the attribute and that will complicate the library a bit. However we are planning on improving how to get the custom claims since now its a bit complex.

**Comment by jeacott1** [comment]
sure - but the old lib uses id tokens, and in order to migrate from one strategy to the next without downtime this lib should be capable of supporting both no?
As an aside, my api is stateless, I need the email scope detail, and AccountNonLocked() AccountNonExpired() info on every request.
are you suggesting I now need to create my own new jwt to carry the data I need instead of it simply being available in a single auth0 one?
