### ISSUE TITLE
documentation issues.

### ISSUE THREAD

**Issue by jeacott1** [auth0/auth0-spring-security-api#3]
I've spent quite some time trying to update from  auth0-spring-api  to this one. 
the instructions don't seem quite right yet.

the old version used to work just fine in my spring-boot webmvc application without me adding @EnableWebSecurity, or @EnableAutoConfiguration but this new one absolutely requires me to explicitly add @EnableWebSecurity. no mention of it in the tutorial. @EnableAutoConfiguration makes no difference in my case.

I see @EnableWebSecurity on your config file, but it doesn't seem to have any effect.

the tutorial says to set auth0.defaultAuth0ApiSecurityEnabled: false
with that set false it doesn't work.

**Comment by arcseldon** [comment]
@jeacott1 - Thank you for the feedback regarding documentation. Yes, `EnableWebSecurity` is used. It is declared in the library `Auth0SecurityConfig.java` file and users are expected to extend that. The same does also reference the same annotation in its `AppConfig.java` file which extends `Auth0SecurityConfig.java` (default if no application specific config declared).

Shall take a look, likely this weekend, and see where we can tighten up on required annotations and associated documentation.  FYI only - if you are using a Spring Boot Web MVC application then this is not the library you should reference.  You `could` use this library (and the libraries are v.similar) but whereas this checks JWT Tokens and behaves as a `receiver` (API) to requests - our -[Auth0 Spring Security MVC](https://github.com/auth0/auth0-spring-security-mvc) library is written specifically with MVC applications in mind. It has an associated [sample](https://github.com/auth0-samples/auth0-spring-security-mvc-sample).

Please let me know how you get on.

**Comment by jeacott** [comment]
The mvc lib appears to have redirects on unauthorized etc and zero option to disable this, hence I'm using this one. My backend is rest+rpc api and some static content.

**Comment by arcseldon** [comment]
Hi @jeacott - thanks for clarifying your server-side app is an API afterall, and not server-side MVC (which is the purpose of the MVC lib). In that case, since it is an API then yes, this library is best choice. So where you mention MVC - is that a SPA application?  If so, here is a sample demonstrating how for example you could set that up using [Angular](https://github.com/auth0-samples/auth0-spring-security-api-client-samples) where the front-end and back-end are on separate servers. If you wish to colocate them (so your backend hosts as the web-server for the front-end) then using Spring Boot for example this is easy - just place the static artifacts inside the resource directory under `static` or `public`.

**Comment by jeacott** [comment]
I'm still using the spring webmvc libs. And all is working fine. Why do u say users are expected to extend auth0securityconfig? Nowhere in the tutorial does it mention that, it says to do the more normal thing and include the package scan. I'd expect to extend WebSecurityConfigurerAdapter for customising security config.  
I'm not sure i see how i can configure multiple auth0 realms using this lib though. And testing is still more awkward that just @withmockuser...

**Comment by arcseldon** [comment]
@jeacott - Pleased to hear it is all working well for you.

The primary difference between the MVC and API is this. Both would work - however, the API works on the understanding that the JWT token passed with each request contains the necessary ROLES claims information. The MVC library will authenticate (verify) the JWT token for secured endpoints and use the UserProfile for GrantedAuthority rights (in other words ROLES permissions).

The `Auth0SecurityConfig` contains all the base configuration to auto-wire together security dependencies and provides a `base` secured endpoint out of the box. For all but the most trivial apps, you'll want to extend this and define your own configuration instead. See the default [here](https://github.com/auth0/auth0-spring-security-mvc/blob/master/src/main/java/com/auth0/spring/security/mvc/Auth0SecurityConfig.java#L173)

And in the sample, we choose to override and provide our [here](https://github.com/auth0-samples/auth0-spring-security-mvc-sample/blob/master/src/main/java/com/auth0/example/AppConfig.java#L27)

Please let me know how you get on, and appreciate the interest and good points you are making. We want our tutorials to be `abc` simple to follow so this is great feedback on areas we can tighten.

**Comment by jeacott** [comment]
I dont think both would work in my case would they? I certainly dont want the mvc unauthorized redirect to happen, and that was my primary reason for choosing this lib. With no docs anywhere explaining the difference and options,  and the surprise ditching of the previous lib, and all docs related to it, and no migration docs offered,  for a version 0.0.3!  It hasn't been the friendliest transition ever.

**Comment by arcseldon** [comment]
@jeacott - Unfortunately, still not clear what your case is - are you building a SPA application that talks to an API backend?  We have put some documentation [here](https://auth0.com/docs/java-overview) on the high level differences - plus the links provided there to each tutorial + the READEM files with each library and at least one sample (sometimes several) for each of those associated libraries. We are still catching up on QuickStarts and improving each of the Java docs specific to each library. Trust me, this is on our radar and shall be completed soon.

We had alot of customers asking us to modernise our Java offering, and introduce modern Java configuration annotations instead of the old style XML configurations. Plus, with the advent of Spring Boot, many customers (in particular those doing Micoservice style architectures) were keen to leverage Spring Boot. To that end, we have done this and had very little negative feedback.

We never `ditched` the old library, but we do not want to encourage its usage anymore as support is now focused on our new offering. However, if you wished to access the old repo (with full history) - get it from this [branch](https://github.com/auth0/auth0-spring-security-mvc/tree/spring-security-auth0-archive/archive).

**Comment by jeacott** [comment]
I found it there previously,  but all the quickstart docs etc for it are gone, and there was no 'hey weve got this new thing, give it a go, here's what u need to know...'. I'm using spring boot w embedded undertow for rest, rpc (spring remoting), websockets (atmosphere), jms, supporting stateless token auth supporting several spa including a react spa and other services.

**Comment by arcseldon** [comment]
@jeacott - quick update. the documentation is still in progress, however we should be getting near completion this week. Our docs team have been working through a backlog across a range of recently updated libraries, SDKs, and core service changes hence the need to prioritise.

How is everything going?

**Comment by adrogon** [comment]
Hello,

I just wanted to mention, about the docs, that the introduction suggests "com.auth0:auth0-spring-security-api:0.0.3" as a dependency, whereas the current version is 0.**3.0**.

It is accurate regarding the provided examples, but it makes quite the difference when looking for the latest version.

Regards,
Anthony.

**Comment by arcseldon** [comment]
@adrogon - thanks for pointing out the docs issue with version. Our docs team have been informed and this should be fixed asap.

**Comment by arcseldon** [comment]
@jeacott - Docs have been updated [here](https://auth0.com/docs/quickstart/backend/java-spring-security)

**Comment by arcseldon** [comment]
Docs updated.
