### ISSUE TITLE
Get details when token validation failed

### ISSUE THREAD

**Issue by jeremieca** [auth0/auth0-spring-security-api#52]
Hi,

Is it possible to know, in error controller (``` public class OnErrorController implements ErrorController ```), why 401 error is raised by Auth0 (expired token, invalid signature, invalid roles...) ?

Thanks !

**Comment by lbalmaceda** [comment]
I don't think I understand your question. If the validation fails by any reason (i.e. the signature is invalid, token expired, etc) the token is not to be trusted and thus, the unauthorized error raises.

**Comment by lbalmaceda** [comment]
"What happened that failed" is something you probably don't want to disclose. A `401` response already says that the authentication failed, meaning that a different token should be used on the next attempt. That should be enough for any user.
If you want to know the reason for server side logging or debugging, the [verification step throws](https://github.com/auth0/auth0-spring-security-api/blob/master/lib/src/main/java/com/auth0/spring/security/api/authentication/PreAuthenticatedAuthenticationJsonWebToken.java#L87) a `JWTVerificationException` with a valid string message or description you can print. This exception is ultimately handled by the Spring context, meaning that's out of this SDK scope.

I don't know how your error handler class is and I'm not that into Spring, but you should be able to obtain that exception and test if it is of type `JWTVerificationException` and in that case, dig into the message. A quick search on google over the `ErrorController` interface says it [doesn't have](https://docs.spring.io/spring-boot/docs/1.5.x-SNAPSHOT/api/org/springframework/boot/autoconfigure/web/ErrorController.html) a method to obtain the exception, but that there are 2 classes implementing this interface already, that you might want to check out and probably extend them instead. Since they expose methods to obtain the error as [ErrorAttributes](https://docs.spring.io/spring-boot/docs/1.5.x-SNAPSHOT/api/org/springframework/boot/autoconfigure/web/ErrorAttributes.html#getError-org.springframework.web.context.request.RequestAttributes-) which end exposing the `Throwable` instance.

If you happen to find an issue regarding this SDK or want to suggest a feature, feel free to open another issue.
Cheers

**Comment by jeremieca** [comment]
Thanks, perfect.
